### ISSUE TITLE
Clean up SymPy output

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#138]
This tends to go back and forth in terms of the line wrapping:
https://github.com/cscherrer/Soss.jl/pull/137/files#diff-04c6e90faac2675aa89e2176d2eec7d8L188

I prefer the unwrapped version (it doesn't seem too long). I think this has to do with the width of the terminal used for `weave`, which is not great. Not clear to me that this is a Weave.jl issue, but maybe there's an environment variable we can set for this?

Ideally, we could also give a precision for the floating point values, currently the number of decimal places is kind of silly.

**Comment by cscherrer** [comment]
Then again, I don't think we should focus too much on SymPy, hopefully we can transition to [SymbolicUtils.jl](https://github.com/JuliaSymbolics/SymbolicUtils.jl).

**Comment by millerjoey** [comment]
Off topic a bit, but is `julia> symlogpdf(m2) |> expandSums |> foldConstants` working as expected in the readme? I don't see a difference between the two expressions.

> Ideally, we could also give a precision for the floating point values, currently the number of decimal places is kind of silly.

For the readme, we can do

```julia
julia> symlogpdf(m2).evalf(2)
                          N                                       k           
                         ___                                     ___          
                         ╲                                       ╲            
                          ╲                            2          ╲          2
-0.92⋅N - 0.92⋅k - 0.5⋅   ╱    (y[_j1] - 1.0⋅yhat[_j1])  - 0.5⋅   ╱    β[_j1] 
                         ╱                                       ╱            
                         ‾‾‾                                     ‾‾‾          
                       _j1 = 1                                 _j1 = 1        

```

or do you mean to add this functionality directly to `symlogpdf`?

**Comment by cscherrer** [comment]
> Off topic a bit, but is `julia> symlogpdf(m2) |> expandSums |> foldConstants` working as expected in the readme? I don't see a difference between the two expressions.

Good catch! Yes, this must be outdated.



> For the readme, we can do...

Nice! Yes, this is much better. Does this change the value itself, or just the printed representation? We should have a `show` method do the latter

**Comment by cscherrer** [comment]
Keep in mind, SymPy is really limited in some ways, mostly when it comes to working with arrays. We'll probably transition to SymbolicUtils at some point, though I do really like how pretty SymPy's output can be

**Comment by millerjoey** [comment]
> Does this change the value itself, or just the printed representation? 

It changes the value, `s.evalf(3) != s`, but doesn't change in-place. So something like this is safe: `Base.show(io::IO, s::SymPy.Sym) = s.evalf(3)`.

Have you dug into SymbolicUtils? Does it seem complete enough yet?

**Comment by cscherrer** [comment]
Haven't dug in much, but I think ModelingToolkit is already using it
