### ISSUE TITLE
Example in README doesn't work

### ISSUE THREAD

**Issue by catethos** [cscherrer/Soss.jl#16]
I am just trying the example in the readme
```julia
hello = @model μ,x begin
              σ ~ HalfCauchy()
              x ~ Normal(μ,σ) |> iid
              end
data = (μ=1, x=[2,4,5])
nuts(hello, data=data).samples
```
But I get the error `ERROR: type NamedTuple has no field x`. Any idea?

**Comment by vtrubets** [comment]
I'm seeing the same error.

Details:
Julia Version 1.0.2 (2018-11-08)
Soss.jl installed from github (master:197f2dd1056d465cafa3862516651afc783f6550)

**Comment by catethos** [comment]
So I finally got some time to mess around and I find out that the following example works
```
hello = @model begin
       μ ⩪ Normal(0,1)
       σ ~ HalfCauchy()
       x ⩪ Normal(μ,σ) |> iid
       end

data = (μ=1,x=[2,4,5])

nuts(hello, data=data).samples # 1000 samples of σ
```
Few differences:
1. Looking at https://github.com/cscherrer/Soss.jl/blob/master/src/utils.jl#L121, it seems that we need to use `⩪` to specify observed data
2. It seems that it doesn't matter what are the variables after the `@model` macro. (Although I thought it should be the variables that I want to sample)

*Note* Looking back the commit history, it seems that this is the old syntax( ⩪), and @cscherrer updated the readme to all use (~), regardless the variable being data or parameter. Maybe this is intended change that has not been implemented?

**Comment by goedman** [comment]
Hi,

Below format also shows the μ draws:

```
using Soss

lr = @model y begin
    μ ~ Normal(0, 5)
    σ ~ HalfCauchy(3)
    x ⩪ Normal(μ, σ) |> iid
end

# This is has mu and sigma as parameters and y as observed, as you can check:

parameters(lr(:x))
observed(lr(:x))

#When you call nuts, you should only be passing in the data, not the parameters, like this:

data = (x=rand(Normal(3, 2), 15),)
nuts(lr, data=data, numSamples=10).samples
```

```
MCMC, adapting ϵ (75 steps)
0.0011 s/step ...done
MCMC, adapting ϵ (25 steps)
3.7e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
0.0022 s/step ...done
MCMC, adapting ϵ (100 steps)
2.6e-5 s/step ...done
MCMC, adapting ϵ (200 steps)
2.6e-5 s/step ...done
MCMC, adapting ϵ (400 steps)
2.4e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
2.7e-5 s/step ...done
MCMC (10 steps)
2.6e-5 s/step ...done
10-element Array{NamedTuple{(:μ, :σ),Tuple{Float64,Float64}},1}:
 (μ = 2.9883562211700845, σ = 1.7598420914668764)
 (μ = 3.222859619195211, σ = 2.2125696283628957) 
 (μ = 3.420934677875722, σ = 1.5835166690786329) 
 (μ = 2.9752317504542796, σ = 1.7118366126765874)
 (μ = 3.0918977417540745, σ = 1.7156380395039268)
 (μ = 3.6418255471523584, σ = 2.6134648555308075)
 (μ = 3.5165133709583785, σ = 2.4652729264355453)
 (μ = 3.0132879378175974, σ = 1.7182786276906663)
 (μ = 3.5299201562063844, σ = 1.7322502051573363)
 (μ = 2.861267349435854, σ = 2.262929847085032)  
```

**Comment by cscherrer** [comment]
I see what's causing the problem on my system:
```julia
julia> logdensity(hello)
:(function (par, data)
      ℓ = 0.0
      σ = par.σ
      ℓ += logpdf(HalfCauchy(), σ)
      x = data.x
      ℓ += logpdf(Normal(μ, σ) |> iid, x)
      return ℓ
  end)
```

This is missing generating a `μ = data.μ`, so when it gets to `μ` it has no idea where to find the value. @catethos can you tell me what the above `logdensity` function returns for you?

**Comment by cscherrer** [comment]
Actually, I might have fixed it. Works now for me, anyway. @catethos can you pull and try again?

**Comment by catethos** [comment]
It is working now. Thank @cscherrer for the quick fix. 
Looking forward to helping more in the spring when you can concentrate on this project :)
