### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by zenon** [cscherrer/Soss.jl#166]
Hi.

Whith the following model

     m1 = @model age begin
	     a = 7.0 # ~ Uniform(0.1, 2.0)
         size ~ For(eachrow(age)) do x
	     	# eachrow gives an array type, so we take the value out of it with x[1]
             Normal(a * x[1], 1.0)
         end
     end

and these data

     ages = collect(range(1.0, 200.0, length = 100))

     m1Forward = m1(age = ages)
     priorSimulation = rand(m1Forward)

Now priorSimulation contains in size the same array as provided in age. I assumed it to produce size values normally distributed around a*age.

Complete code here
https://github.com/zenon/sosstest/blob/master/sosstest02.jl

A hint to where I'm wrong would make me happy.

Thank you, and kind greetings, 

z.

**Comment by cscherrer** [comment]
This seems right to me. I'd probably go for `eachindex` instead of `eachrow` so you don't have to unwrap at each step. But as written I get this:


```
julia> scatterplot(ages, priorSimulation.size .- ages .* priorSimulation.a)
      ┌────────────────────────────────────────┐ 
    3 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⡀⠀⠀│ 
      │⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
      │⠀⠀⠀⠀⠄⠀⠄⠀⠀⠀⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠄⠀⠀⠀⡐⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⢀⠀⠀⠀⠀⠀⠀⠀⠐⠀⠀⠀⠀│ 
      │⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠠⠀⠀⠂⠀⠀⠂│ 
      │⢀⠀⢀⠄⠀⠀⠀⠀⠈⠀⠐⠀⠀⠀⠠⠀⠀⠀⠀⠠⡀⠀⠀⠁⠀⠀⠀⠀⠀⢀⠈⠐⠀⠀⠀⠐⠀⠀⠀⠀│ 
      │⠤⠦⠤⠤⠤⠤⠤⠦⠥⠬⠤⠤⠤⠦⠤⠴⠤⠦⠤⠤⠤⠤⠤⢤⢤⠤⠤⠤⠤⠴⠤⠤⠦⠴⠤⠤⠤⠤⠴⢴│ 
      │⠀⠂⠀⢀⠀⠄⢀⠌⠀⠁⠀⠀⠄⠀⠀⡀⠈⠀⠐⡀⠐⠀⠀⠀⠀⠀⠀⠐⠀⠀⠀⡀⠀⠀⠐⠀⠀⠀⠀⠀│ 
      │⠄⠀⠁⠀⠀⠐⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠐⠀⠀⠀⠀⠁⠀⠄⠠⡠⠀⠄⠀⠄⠀⠀⠀⠁⠀⠀⠈⠀⠀│ 
      │⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠄⠐⠀⠀⠀⠂⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠂⠀│ 
      │⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀│ 
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
   -3 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
      └────────────────────────────────────────┘ 
      0                                      200
```

Is that what you get? How is this different than what you'd expect?

**Comment by zenon** [comment]
Hello Chad,

thank you for the answer.

This is funny. I see something completely different.

     sum(pairs(priorSimulation)[:age] .- pairs(priorSimulation)[:size]) 

gives zero. Both arrays are the same.

But when I use your suggestion with eachindex, and add a factor of 2 [Wat ???], I still get a different picture than you, but am in the ballpark.

scatterplot(ages, priorSimulation.size .- ages .* priorSimulation.a ./ 2)

     ┌────────────────────────────────────────┐
    5 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⡀⠀⠀⠀⢀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⢀⠀⠀⡐⠀⠀⠀⠀⠐⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠈⠠⠀⠀⠂⠀⡂⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⡀⠀⠀⠁⠠⠀⠈⠀⠠⠀⢀⠀⠐⠀⠀⡀⠀⠀⡐⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠁⠀⡀⠀⠀⠀⠀⠀⠁⢀⠂⠀⠀⠀⠀⠀⠂⠄⠂⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠁⠀⠀⠀⠀⠀⠄⠀⠁⠀⠀⡀⠀⠀⠁⠀⠀⡀⠈⠀⠀⠁⠈⠐⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠂⠀⠀⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠠⠀⠠⠀⠀⠀⠄⠂⠪⠀⠠⠁⠀⠀⠀⠀⠈⠀⠀│
      │⠀⠀⠀⠀⠐⠀⠀⠀⠀⠀⠀⠀⢀⡄⢀⠁⢀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡀⠀⠀⠀⡀⠠⠀⢀⠂⠀⢀⠀⠀⠠│
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠀⠀⠀⡀⠀⠀⠈⠈⠀⠀⠀⠐⠡⠀⠠⠀⠀⠁⠀│
      │⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠬⠤⠤⠤⠤⢤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⡤⠬⠤│
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠊⠄⠐⠀⠁│
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
   -2 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠂⠀⠀⢀⠀⠀⠀⠀⠀│
      └────────────────────────────────────────┘
      0                                      200

julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)


(soss) pkg> status
Status `C:\projects\plutoJL\soss\Project.toml`
  [336ed68f] CSV v0.7.7
  [a93c6f00] DataFrames v0.21.5
  [31c24e10] Distributions v0.23.4
  [91a5bcdd] Plots v1.5.8
  [8ce77f84] Soss v0.12.0
  [f3b207a7] StatsPlots v0.14.7
  [b8865327] UnicodePlots v1.1.0

Kind greetings, z.

**Comment by cscherrer** [comment]
That... is really weird.

You can see the generated code like this:
```julia
julia> Soss.sourceRand()(m1)
quote
    a = 7.0
    size = rand(For(((x,)->begin
                        #= REPL[6]:5 =#
                        Normal(a * x[1], 1.0)
                    end), eachrow(age)))
    (age = age, a = a, size = size)
end
```

We can build a `For` in this way...

```julia
julia> dist = For(((x,)->begin
           Normal(a * x[1], 1.0)
       end), eachrow(age));
```

A `For` is like a lazy `map`, with a function and a domain:
```julia
julia> propertynames(dist)
(:f, :θ)
```

Upon evaluation, it turns into something like
```julia
julia> dist.f.(dist.θ)
100-element Array{Normal{Float64},1}:
 Normal{Float64}(μ=7.0, σ=1.0)
 Normal{Float64}(μ=21.07070707070707, σ=1.0)
 Normal{Float64}(μ=35.14141414141414, σ=1.0)
 Normal{Float64}(μ=49.21212121212121, σ=1.0)
 ⋮
```

Oh! But it looks like we're currently calling the wrong thing in the case where θ is a `Generator`:

```julia
@inline function rand(d :: For{F,T,D,X}) where {F,T <: Base.Generator, D, X}
    rand.(Base.Generator(d.θ.f, d.θ.iter))
end
```

This never uses `d.f`, which explains the different results.

We'll need to fix this right away. Thanks for reporting this @zenon !

**Comment by cscherrer** [comment]
On a closer look, this seems to be fixed in `master`:
```julia
@inline function rand(d::For{F,T,D,X}) where {F,T<:Base.Generator,D,X}
    return rand.(Base.Generator(d.f, d.θ))
end
```

**Comment by zenon** [comment]
Should this be solved with 0.13.0? (It isn't.)

**Comment by DilumAluthge** [comment]
It should be fixed in 0.13.0. Can you post the output of `import Pkg; Pkg.status(; mode = Pkg.PKGMODE_MANIFEST)`?

**Comment by zenon** [comment]
julia> import Pkg; Pkg.status(; mode = Pkg.PKGMODE_MANIFEST)
Status `C:\projects\plutoJL\soss\Manifest.toml`
  [621f4979] AbstractFFTs v0.5.0
  [398f06c4] AbstractLattices v0.2.1
  [79e6a3ab] Adapt v2.0.2
  [0bf59076] AdvancedHMC v0.2.25
  [dce04be8] ArgCheck v2.1.0
  [7d9fca2a] Arpack v0.4.0
  [68821587] Arpack_jll v3.5.0+3
  [4fba245c] ArrayInterface v2.11.0
  [4c555306] ArrayLayouts v0.3.8
  [13072b0f] AxisAlgorithms v1.0.0
  [6e4b80f9] BenchmarkTools v0.5.0
  [6e34b625] Bzip2_jll v1.0.6+3
  [336ed68f] CSV v0.7.7
  [a603d957] CanonicalTraits v0.2.2
  [324d7699] CategoricalArrays v0.8.1
  [aaaa29a8] Clustering v0.14.1
  [35d6a980] ColorSchemes v3.9.0
  [3da002f7] ColorTypes v0.10.8
  [5ae59095] Colors v0.12.3
  [861a8166] Combinatorics v1.0.2
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.14.0
  [e66e0078] CompilerSupportLibraries_jll v0.3.3+0
  [8f4d0f93] Conda v1.4.1
  [187b0558] ConstructionBase v1.0.0
  [d38c429a] Contour v0.5.4
  [adafc99b] CpuId v0.2.2
  [9a962f9c] DataAPI v1.3.0
  [a93c6f00] DataFrames v0.21.5
  [864edb3b] DataStructures v0.17.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [e7dc6d0d] DataValues v0.4.13
  [163ba53b] DiffResults v1.0.2
  [b552c78f] DiffRules v1.0.1
  [b4f34e82] Distances v0.9.0
  [31c24e10] Distributions v0.23.4
  [ffbed154] DocStringExtensions v0.8.2
  [bbc10e6e] DynamicHMC v2.1.5
  [e2ba6199] ExprTools v0.1.1
  [8f5d6c58] EzXML v1.1.0
  [c87230d0] FFMPEG v0.3.0
  [b22a6f82] FFMPEG_jll v4.3.1+1
  [7a1cc6ca] FFTW v1.2.2
  [f5851436] FFTW_jll v3.3.9+5
  [1a297f60] FillArrays v0.8.14
  [6a86dc24] FiniteDiff v2.5.2
  [53c48c17] FixedPointNumbers v0.8.4
  [b67e1e5a] FlexLinearAlgebra v0.1.0
  [f6369f11] ForwardDiff v0.10.12
  [d7e528f0] FreeType2_jll v2.10.1+3
  [559328eb] FriBidi_jll v1.0.5+4
  [069b7b12] FunctionWrappers v1.1.1
  [28b8d3ca] GR v0.51.0
  [6b9d7cbe] GeneralizedGenerated v0.2.5
  [14197337] GenericLinearAlgebra v0.2.4
  [5c1252a2] GeometryBasics v0.2.15
  [4d00f742] GeometryTypes v0.8.3
  [86223c79] Graphs v0.10.3
  [cd3eb016] HTTP v0.8.17
  [83e8ac13] IniFile v0.5.0
  [505f98c9] InplaceOps v0.3.0
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+0
  [a98d9a8b] Interpolations v0.12.10
  [d8418881] Intervals v1.4.2
  [41ab1584] InvertedIndices v1.0.0
  [c8e1da08] IterTools v1.3.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [682c06a0] JSON v0.21.0
  [b14d175d] JuliaVariables v0.2.3
  [5ab0869b] KernelDensity v0.5.1
  [c1c5ebd0] LAME_jll v3.100.0+2
  [5078a376] LazyArrays v0.16.16
  [dd192d2f] LibVPX_jll v1.9.0+0
  [94ce4f54] Libiconv_jll v1.16.0+5
  [9c8b4983] LightXML v0.9.0
  [d3d80556] LineSearches v7.0.1
  [9b3f67b0] LinearAlgebraX v0.0.8
  [6fdf6af0] LogDensityProblems v0.10.3
  [856f044c] MKL_jll v2020.2.254+0
  [d8e11817] MLStyle v0.4.6
  [1914dd2f] MacroTools v0.5.5
  [a3b82374] MatrixFactorizations v0.5.2
  [739be429] MbedTLS v1.0.2
  [c8ffd9c3] MbedTLS_jll v2.16.6+1
  [442fdcdd] Measures v0.3.1
  [e1d29d7a] Missings v0.4.3
  [78c3b35d] Mocking v0.7.1
  [7475f97c] Mods v1.1.1
  [0987c9cc] MonteCarloMeasurements v0.9.5
  [6f286f6a] MultivariateStats v0.7.0
  [d41bc354] NLSolversBase v7.7.0
  [77ba4419] NaNMath v0.3.4
  [71a1bf82] NameResolution v0.1.4
  [d9ec5142] NamedTupleTools v0.13.6
  [b8a86587] NearestNeighbors v0.4.6
  [510215fc] Observables v0.3.1
  [6fe1bfb0] OffsetArrays v1.1.2
  [e7412a2a] Ogg_jll v1.3.4+1
  [4536629a] OpenBLAS_jll v0.3.9+5
  [458c3c95] OpenSSL_jll v1.1.1+5
  [efe28fd5] OpenSpecFun_jll v0.5.3+3
  [429524aa] Optim v0.20.6
  [91d4177d] Opus_jll v1.3.1+2
  [bac558e1] OrderedCollections v1.3.0
  [90014a1f] PDMats v0.9.12
  [d96e819e] Parameters v0.12.1
  [69de0a69] Parsers v1.0.10
  [2ae35dd2] Permutations v0.4.0
  [ccf2f8ad] PlotThemes v2.0.0
  [995b91a9] PlotUtils v1.0.5
  [91a5bcdd] Plots v1.5.8
  [f27b6e38] Polynomials v1.1.4
  [2dfb63ee] PooledArrays v0.5.3
  [85a6dd25] PositiveFactorizations v0.2.3
  [8162dcfd] PrettyPrint v0.2.0
  [27ebfcd6] Primes v0.5.0
  [92933f4c] ProgressMeter v1.3.2
  [438e738f] PyCall v1.91.4
  [1fd47b50] QuadGK v2.4.0
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v1.0.2
  [01d81517] RecipesPipeline v0.1.12
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v1.0.1
  [37e2e3b7] ReverseDiff v1.4.2
  [79098fc4] Rmath v0.6.1
  [f50d1b31] Rmath_jll v0.2.2+1
  [21efa798] SIMDPirates v0.8.24
  [476501e8] SLEEFPirates v0.5.5
  [91c51154] SentinelArrays v1.2.11
  [efcf1570] Setfield v0.7.0
  [992d4aef] Showoff v0.3.1
  [55797a34] SimpleGraphs v0.5.0
  [ec83eff0] SimplePartitions v0.3.0
  [cc47b68c] SimplePolynomials v0.2.2
  [b2aef97b] SimplePosets v0.1.2
  [a6525b86] SimpleRandom v0.2.1
  [a2af1166] SortingAlgorithms v0.3.1
  [8ce77f84] Soss v0.13.0
  [276daf66] SpecialFunctions v0.10.3
  [90137ffa] StaticArrays v0.12.4
  [2913bbd2] StatsBase v0.33.0
  [4c63d2b9] StatsFuns v0.9.5
  [f3b207a7] StatsPlots v0.14.7
  [09ab397b] StructArrays v0.4.4
  [24249f21] SymPy v1.0.27
  [ab02a1b2] TableOperations v0.2.1
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v1.0.5
  [f269a46b] TimeZones v1.3.2
  [84d833dd] TransformVariables v0.3.8
  [3a884ed6] UnPack v1.0.2
  [b8865327] UnicodePlots v1.1.0
  [3d5dd08c] VectorizationBase v0.12.32
  [81def892] VersionParsing v1.2.0
  [cc8bc4a8] Widgets v0.6.2
  [efce3f68] WoodburyMatrices v0.5.2
  [02c8fc9c] XML2_jll v2.9.10+1
  [83775a58] Zlib_jll v1.2.11+15
  [0ac62f75] libass_jll v0.14.0+3
  [f638f0a6] libfdk_aac_jll v0.1.6+3
  [f27f6e37] libvorbis_jll v1.3.6+5
  [1270edf5] x264_jll v2020.7.14+1
  [dfaa095f] x265_jll v3.0.0+2
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [4607b0f0] SuiteSparse
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode

**Comment by DilumAluthge** [comment]
@cscherrer Looks like this bug was not fixed in 0.13.0?

**Comment by zenon** [comment]
Oh. Now we have a 0.13.1. Still not fixed for me with it.

**Comment by cscherrer** [comment]
Hmm that's really weird. I think we need a minimal way to reproduce this, maybe something like

1. Manually construct the `For` instance
2. Confirm that `rand` gives the incorrect result
3. Confirm which code it's calling

I have to run now to attend to some other things, but I can give details on this later if it's not clear

**Comment by zenon** [comment]
Thank you for the attention :-)



     a = 7.0
     age = collect(range(1.0, 10.0, length = 5))
     
     dist = For(((x,)->begin
                  Normal(a * x[1], 1.0)
              end), eachindex(age));

now

     propertynames(dist)

gives (:f, :θ), as you mentioned above.

However,

     dist.f.(dist.θ)

gives only one line, not 5 as I expected:

     (Normal{Float64}(μ=7.0, σ=1.0),)

And now I don't know what next :-)

**Comment by cscherrer** [comment]
Thanks @zenon , can you confirm the result of `rand(dist)` in this case?

The way this works is, building one of these with `dist = For(f,θ)` (or `dist = For(θ) do x f(x) end`) instantiates one of these:

```julia
struct For{F,T,D,X}
    f::F
    θ::T
end
```

The method called by `rand(dist)` is different depending on which `T` is used.

The `T` you had before was a `Base.Generator`, but this one is a `Tuple{Base.OneTo{Int64}}`. Compare:

```julia
julia> eachindex(age) |> typeof
Base.OneTo{Int64}

julia> (sqrt(a) for a in eachindex(age)) |> typeof
Base.Generator{Base.OneTo{Int64},typeof(sqrt)}
```

Let's build a `dist` for each and make sure we know which `rand(dist)` is causing trouble. Then `@edit rand(dist)` to be sure we know which code is being called. Make sense?

**Comment by zenon** [comment]
julia> rand(dist)
5-element Array{Float64,1}:
  5.821063379554319
 13.910171730146875
 21.103925060985418
 28.764339577367156
 34.93158017549357


julia> eachindex(age) |> typeof
Base.OneTo{Int64}

julia> (sqrt(a) for a in eachindex(age)) |> typeof
Base.Generator{Base.OneTo{Int64},typeof(sqrt)}

**Comment by zenon** [comment]
Hm. I wondered.

eachindex gives integers back.

Seems the confusing thing was me just using an array proportional to the indices. And then using the indices instead of the values.

This distributions

julia> dist2 = For(((n,)->begin
                     Normal(a * age[n], 1.0)
                 end), eachindex(age));

produces

julia> rand(dist2)
5-element Array{Float64,1}:
  6.410046505213218
 22.138259806223427
 40.351276596850624
 56.0018374211449
 71.46440989737853

As expected. This is how my model should read:

m1 = @model age begin
	a = 7.0 # ~ Uniform(0.1, 2.0)
	# eachrow gives an array type, so we take the value out of it with x[1]
    size ~ For(eachindex(age)) do n
        Normal(a * age[n], 1.0)
    end
end

I'm sorry for the confusion I caused.

Thank you for the help! I'll still have to reread your answers until I understand all the details. But well. It's working.

**Comment by cscherrer** [comment]
> I'm sorry for the confusion I caused.

Please, don't be! I'm glad to hear it's working as expected.

**Comment by zenon** [comment]
:-)
