### ISSUE TITLE
Move all the Python stuff to the new `SossSymPy.jl` package

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/Soss.jl#170]
Would it be possible to eventually remove the dependency on Python?

cc: @cscherrer

**Comment by cscherrer** [comment]
I'd really like to. This is just for `SymPy`. Ideally we could separate this to a SossSymPy package

**Comment by DilumAluthge** [comment]
The first half of this is done. The code still lives in this repository, but the files are no longer `include`d.

 The second half of this will happen soon. Specifically we'll create the SossSymPy.jl package and move the relevant code files into that package.

**Comment by cscherrer** [comment]
@DilumAluthge with SymbolicUtils and now Symbolics available, I think we can drop SymPy altogether

**Comment by DilumAluthge** [comment]
🎉
