### ISSUE TITLE
TODO: Switch from Travis CI to GitHub Actions CI

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/Soss.jl#172]
@cscherrer What do you think about switching from Travis CI to GitHub Actions CI? Usually, GitHub Actions CI will be faster to start jobs (especially during the daytime on weekdays), and they allow more concurrent jobs than Travis.

You'd need to create an additional Documenter key-pair, adding the private key as a GitHub Secret named `DOCUMENTER_KEY`, and the public key as a deploy key with write access. Basically the same instructions as https://github.com/cscherrer/SossMLJ.jl/issues/18

**Comment by cscherrer** [comment]
Sure, I'll get this going. Thanks for the suggestion

**Comment by DilumAluthge** [comment]
Let me know once you've added the Documenter key, and I'll make the PR to set up the CI workflow files.

**Comment by cscherrer** [comment]
Done! @DilumAluthge can you close this when you confirm it's working?

**Comment by DilumAluthge** [comment]
> Done! @DilumAluthge can you close this when you confirm it's working?

Will do!
