### ISSUE TITLE
GitHub repository settings: repo website

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/Soss.jl#174]
@cscherrer Can you edit the repository settings for the `cscherrer/Soss.jl` repository and make the GitHub repository website the following:
- https://cscherrer.github.io/Soss.jl/stable/

**Comment by cscherrer** [comment]
Would this be under "custom domain" here?

![custom-domain](https://user-images.githubusercontent.com/1184449/91735768-9f963d80-eb61-11ea-858f-73100361ee7c.png)

**Comment by DilumAluthge** [comment]
Hmm. It should be the same place that you edit the description of the repository.

**Comment by DilumAluthge** [comment]
If you go to the home page of the repo, near the description there should be an edit button? That should allow you to edit both the description and the website.

**Comment by cscherrer** [comment]
Ok this is super weird. `github.github.io`? And it's not editable

![repo-details](https://user-images.githubusercontent.com/1184449/91759109-f4e44600-eb85-11ea-8cd0-341c8c8b3ae7.png)

**Comment by DilumAluthge** [comment]
That's definitely where you would change it.

Maybe try a different web browser?

If all else fails, might need to contact GitHub support

**Comment by DilumAluthge** [comment]
Are you sure that box isn't editable? What happens if you click in it and try to enter something?

**Comment by cscherrer** [comment]
Done! (finally) :)
