### ISSUE TITLE
TODO: Update branch protection settings for the `master` branch

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/Soss.jl#185]
Now that we use GitHub Actions for CI (instead of Travis CI), we need to update the branch protection settings for the `master` branch:

1. Go to https://github.com/cscherrer/Soss.jl/settings/branches
2. In the row that says `master`, click on the `Edit` button
3. Check the "Require status checks to pass before merging" checkbox.
4. Check the "Require branches to be up to date before merging" checkbox. This ensures that we will never have any [semantic conflicts](https://bors.tech/essay/2017/02/02/pitch/).
5. In the "Status checks found in the last week for this repository" section, check only the following checkboxes:
    - [ ] "Documentation"
    - [ ] "Julia 1 - ubuntu-latest - x64 - pull_request"
    - [ ] "codecov/patch"
    - [ ] "codecov/project"
6. At the bottom of the page, click the green "Save changes" button.

cc: @cscherrer

**Comment by cscherrer** [comment]
Ok, done. Just to confirm, do we really want bots like CompatHelper and TagBot to be unchecked?

**Comment by DilumAluthge** [comment]
> Ok, done. Just to confirm, do we really want bots like CompatHelper and TagBot to be unchecked?

Yeah it seems counterintuitive, right? The problem is that those bots on run on cron jobs. They never actually run on pull requests, meaning that they never report statuses on pull requests. So if you check the box for one of those bots, you'll never be able to merge any PRs, because the bot will never report a status on any PR. (They always report their status on the master branch only.)
