### ISSUE TITLE
Workflow for tests, PRs, etc

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#207]
I'm open to suggestions here, but maybe to start we could do something like

1. We find a bug
2. Add an issue
3. Have a PR with a test that's expected to fail
4. Merging a PR that fixes the test should close the issue

There's a lot about this workflow I'm not sure about. Does this need to be two different PRs? Is there any way to automate parts of this? Do the issue and test-fail PR really need to be two different steps?

cc: @millerjoey @DilumAluthge

**Comment by DilumAluthge** [comment]
I think this would be sufficient:
1. We find a bug
2. Open an issue with a MWE to reproduce the bug
3. Open a PR that fixes the bug. The PR should add a regression test that passes. When the PR is merged, it closes the issue.
