### ISSUE TITLE
Computing supports and variable transformations

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#21]
Some statistical modeling approaches rely on transforming variables to ℝⁿ. For example, if `y ~ Gamma()` we may instead work in terms of `log(y)`. We can reason about this example statically from the AST (just have a function on symbols that takes `:Gamma` to `log`), and in general if we had a fixed set of distributions this would be no problem. It's more difficult when we have something like `y ~ f(x)`; we need to know `x`, evaluate `f(x)` to determine a distribution, and then find the transformation for _that_.

One way to address this (and the best I have thought of so far) is to a sort of abstract interpretation based on random sampling from the model. This could, for example, turn `y ~ f(x)` into

```julia
dist = f(x)
y = rand(dist)
xforms[:y] = getTransform(dist)
```

where `xforms` is a dictionary of the transformations that need to be done. 

Because this determines transformations based on a random sample, it requires an additional restriction that **supports must be static** and cannot change from one execution to the next.

I'm using @thautwarm's [MLStyle.jl](https://github.com/thautwarm/MLStyle.jl) quite a lot, and had thought a nice approach would be to use this to build a [little interpreter](https://github.com/cscherrer/Interpret.jl) to hook into.

But as I type this, the problem seems less challenging than it originally had. [Nice side effect of writing it down. Note to self: write more things down] 

So for now I'll stick with the approach that has been working so far: generate code, `@eval`, and then `invokelatest`. There are clear problems with this -- global evaluation, execution overhead -- but we can keep hunting for a better approach and migrate everything to a new approach if an alternative becomes clear.

**Comment by cscherrer** [comment]
I got it working!
https://github.com/cscherrer/Soss.jl/pull/22

**Comment by thautwarm** [comment]
Oh, congratulations! I was still review those related knowledge for I didn't understand `y~f(x)` well...

**Comment by cscherrer** [comment]
Thanks @thautwarm! 
`x ~ D` notation means "variable `x` follows distribution `D`". For example, say we're flipping a coin. This is a `Bernoulli(p)` distribution, where we could interpret `p` as the probability the coin lands on heads.

If we have `x ~ Bernoulli(p)` we might do things like

- Flip the coin (`rand`), or
- For a given `p`, ask "would we be surprised to see this or that `x` as a result?", or
- For a given `x`, ask "which `p` tend to lead to observations like this?"

These different kinds of questions lead to different ways to manipulate the AST

**Comment by thautwarm** [comment]
Okay, thank you. I think your explanations are concise and succeed in reminding me of some knowledge.

Would it be sufficient to generate the characteristic functions/density functions from `y~f(x)`. 
Assume `f` to be a high order function, accepting a few parameters and returning the characteristic function/probability density function?

**Comment by thautwarm** [comment]
Could sourceXform be implemented as a generated function to avoid invokelatest?

https://github.com/cscherrer/Soss.jl/blob/c26f7
47236b119c199158d2d4fba6df847784c1d/src/xform.jl#L54
