### ISSUE TITLE
Find a way around `invokelatest`

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#23]
I've been using `invokelatest` for quite a while. This is definitely a hack. It evaluates in global scope, has a been of additional overhead, and is generally discouraged.

@thautwarm offered to have a look at this (THANK YOU!!!) to see if there might be a workaround.

Simplest place to start is here:
https://github.com/cscherrer/Soss.jl/blob/master/src/rand.jl

The current approach is 
1. `sourceRand` generates the source code
2. `makeRand` uses `invokelatest` to create the function
3. `rand` is a little wrapper that's intended to be similar to `Base.rand`
 
For example, here's a little coin flip model:
```julia
julia> coin
@model flips begin
        pHeads ~ Beta(1, 1)
        flips ~ Bernoulli(pHeads) |> iid(20)
    end
```

Here's the source code:

```julia
julia> sourceRand(coin)
:(function ##rand#397(args...; kwargs...)
      @unpack () = kwargs
      pHeads = rand(Beta(1, 1))
      flips = rand(iid(20, Bernoulli(pHeads)))
      (flips = flips, pHeads = pHeads)
  end)
```

And sampling from it:
```julia
julia> rand(coin)
(flips = [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1], pHeads = 0.65847447186616)
```

**Comment by cscherrer** [comment]
This seems to be a common problem for Julia DSL developers. Currently using `invokefrozen` as described [here](https://discourse.julialang.org/t/codegen-woes/27098), seems to be working well

**Comment by thautwarm** [comment]
Hello Chad, sorry that I didn't response for long.
I 'm now dealing with my research tasks(exactly my recent commits) and it've already taken a month from my life.
I still think generated function could help with this problem. Although generated functions cannot hold any closure or impure/side-effect process, we do can avoid them by making impure stuffs parametric or implementing closures ourselves.
The `coin` here is an AST, but I can transform it into an immutable datatype instance holding the necessary information for codegen. Then I can make `sourceRand` a generated function, which generates a state/parameter(hereafter as S) identical to your expected generated function. This is called the defunctionisation. If we make S a dedicated structure, we can make it callable `(s::S)(args...;kwargs...)=...`, and in this function we can introduce side effects like random generations in.
Let me try in 3 days.

**Comment by cscherrer** [comment]
No worries! I don't understand it deeply enough to implement myself, but it sounds like it could work.

My two big goals for this are
1. Improve performance
2. Make it easy for people to build new inference methods, without needing a deep understanding of the entire system.

I'll be putting together a submission for the JuliaCon proceedings, which are due August 31. If this works a little bit by then I'll attribute to you in a Future Work section. 

Even better, if 

- We get the whole thing working, 
- It addresses the goals, and 
- We can write it up in time...

That would be a dramatic improvement and major contribution to the project. In that case I hope you'd consider joining me as co-author

**Comment by thautwarm** [comment]
Understood the case. I'll start tomorrow, and if I get things working we can discuss further.

I'll try to achieve your two big goals and the needed code will not be large.

**Comment by cscherrer** [comment]
Great, thanks! The current implementation doesn't allow for closures, but that's more just how it worked out than an intentional design choice. I'm open to changing the semantics if it improves things, especially if it makes things more expressive or easy to reason about. Happy to chat further about this, just let me know.

**Comment by cscherrer** [comment]
Closing because WE DID IT!!
