### ISSUE TITLE
Collision of filenames on OS X

### ISSUE THREAD

**Issue by sethaxen** [cscherrer/Soss.jl#299]
On OS X, filenames are not case sensitive, so `scratchpad/vis.jl` and `scratchpad/VIS.jl`, upon cloning, collide, which makes working with git more challenging (one cannot stash all changes, for example).

**Comment by cscherrer** [comment]
Huh, I had no idea. I'll update one to `vis2.jl`

**Comment by cscherrer** [comment]
Ok, done. Can you close this after confirming it's resolved?

**Comment by sethaxen** [comment]
Fixed for me!
