### ISSUE TITLE
Precompilation warning

### ISSUE THREAD

**Issue by sethaxen** [cscherrer/Soss.jl#335]
With the latest version of Soss, I'm getting the following warning while precompiling Soss in a fresh environment:
```julia
[ Info: Precompiling Soss [8ce77f84-9b61-11e8-39ff-d17a774bf41c]
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for Soss [8ce77f84-9b61-11e8-39ff-d17a774bf41c]
│   exception = Required dependency TransformVariables [84d833dd-6860-57f9-a1a7-6da5db126cff] failed to load from a cache file.
```

**Comment by cscherrer** [comment]
Thanks. Are you familiar with warnings like this? I'm not seeing it in Julia 1.7 or 1.8. Could it be a TransformVariables issue?

**Comment by sethaxen** [comment]
I came across https://discourse.julialang.org/t/seemingly-random-precompilation-errors-does-not-support-precompilation-but-is-imported-by-a-module-that-does/360/6, and inspired by it, I deleted Soss, SampleChains, SampleChainsDynamicHMC, MeasureTheory, and TransformVariables from `~/.julia/compiled` and from `~/.julia/packages`. Not certain which of those fixed it, but the error is gone now, so it seems to have been an issue on my machine.
