### ISSUE TITLE
Empty transform with (new) Soss.as

### ISSUE THREAD

**Issue by marius311** [cscherrer/Soss.jl#342]
Looks like `Soss.xform` was recently replaced with `Soss.as`. I updated MuseInference accordingly, but now I see an error which I can track down to that the following produces an empty transform, whereas before it (correctly, I think?) contained a transform on `z`: 

```julia
model = Soss.@model () begin
    z ~ Distributions.MvNormal(zeros(10), I)
end
Soss.as(model()) # empty transform tuple
```

Any help on if this is a bug or an API update appreciated!

**Comment by cscherrer** [comment]
Hi @marius311 , sorry to leave you hanging. Digging into this now...

**Comment by cscherrer** [comment]
I fixed it up, and added this to the tests:
```julia
    @testset "https://github.com/cscherrer/Soss.jl/issues/342" begin
        m = Soss.@model () begin
            z ~ Dists.MvNormal(zeros(10), I)
        end
        t = Soss.as(m()) 
        @test TV.transform(t, zeros(10)) == (z = zeros(10), )
    end
```

**Comment by marius311** [comment]
Awesome, thanks! Will take a look.
