### ISSUE TITLE
Support for non-unit RealIntervals

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#36]
@ode33 noticed a model using `σ ~ Uniform(0,50)` throwing this error:

```julia
ERROR: LoadError: asTransform(RealInterval(0.0, 50.0)) not yet supported
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] asTransform(::RealInterval) at /home/oliver/.julia/packages/Soss/bC3jk/src/xform.jl:76
```

**Comment by ode33** [comment]
Yes from here 
```
function asTransform(supp:: RealInterval)
    (lb, ub) = (supp.lb, supp.ub)

    (lb, ub) == (-Inf, Inf) && (return asℝ)
    (lb, ub) == (0.0,  Inf) && (return asℝ₊)
    (lb, ub) == (0.0,  1.0) && (return as𝕀)
    error("asTransform($supp) not yet supported")
end
```
it happens that:
```
julia> support(Uniform(0,50)).ub
50.0
julia> support(Uniform(0,50)).lb
0.0
```

**Comment by cscherrer** [comment]
This results from this code in `xform.jl`:
```julia
function asTransform(supp:: RealInterval) 
    (lb, ub) = (supp.lb, supp.ub)

    (lb, ub) == (-Inf, Inf) && (return asℝ)
    (lb, ub) == (0.0,  Inf) && (return asℝ₊)
    (lb, ub) == (0.0,  1.0) && (return as𝕀)
    error("asTransform($supp) not yet supported")
end
```

Currently we only support cases where the support doesn't depend on runtime data. Solution is to add the appropriate `TransformVariables.jl` function for the general finite case (though it will still be static, at least for now)

**Comment by ode33** [comment]
I suppose an `else` exception for the `Uniform` distribution could be created here
```
function xform(d)
    if hasmethod(support, (typeof(d),))
        return asTransform(support(d))
    end
end
```
perhaps something like
```
xform(d) = (typeof(d) == Uniform{Float64} && return asℜ) || 
            (hasmethod(support, (typeof(d),)) && return asTransform(support(d)))

**Comment by cscherrer** [comment]
`xform` maps ℝⁿ into the support of a given distribution. So for a `Uniform`, it needs to be `as𝕀` composed with maybe translation and scaling

**Comment by cscherrer** [comment]
Aha!
https://tamaspapp.eu/TransformVariables.jl/dev/#TransformVariables.ScaledShiftedLogistic

**Comment by cscherrer** [comment]
https://github.com/cscherrer/Soss.jl/commit/a87056b7ba29877ff0e3e21111a89f8c6e82df32

Please re-open if this doesn't fix it

**Comment by cscherrer** [comment]
Oops nope it doesn't. Testing now

**Comment by cscherrer** [comment]
Ok , https://github.com/cscherrer/Soss.jl/commit/3861c2864028f257f583f3d573c8022a494be30a

Now this works:
```julia
using Soss

m = @model begin
    μ ~ Uniform(-2,3)
    x ~ Normal(μ,x)
end

julia> nuts(m(), (x=0.2,)) |> particles
(μ = 0.2 ± 0.21,)
```
