### ISSUE TITLE
Using values outside Soss

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#42]
This doesn't work:

```julia
julia> f(x) = x+1
f (generic function with 1 method)

julia> m = @model begin
           y = f(x)
           x ~ Normal(y,1)
       end;

julia> rand(m())
ERROR: UndefVarError: y not defined
```

I'm guessing it could be a very hard problem to fix. Maybe we should implement `$` interpolation inside a `@model`?

**Comment by ode33** [comment]
In CmdStan.jl the model is passed to the compiler as a string. Is that what you mean by `$` interpolation?

**Comment by cscherrer** [comment]
We try to avoid "stringly-typed" code ;)

More like this:
```julia
julia> y = :(x+1)
:(x + 1)

julia> :(z + $y)
:(z + (x + 1))

julia> :(z + $y) |> dump
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol +
    2: Symbol z
    3: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol +
        2: Symbol x
        3: Int64 1
```

**Comment by cscherrer** [comment]
@thautwarm do you have ideas that could help with this?

**Comment by thautwarm** [comment]
What's the generated code for this model?@cscherrer

**Comment by thautwarm** [comment]
Besides, 
> Maybe we should implement $ interpolation inside a @model?

It's possible for people to define the function ouside model definitions and insert it. 
Is it what you want?
If so, it wouldn't be hard IMO.

**Comment by cscherrer** [comment]
> What's the generated code for this model?

```julia
julia> sourceRand()(m)
quote
    x = rand(Normal(y, 1))
    y = f(x)
    (y = y, x = x)
end

julia> rand(m())
ERROR: UndefVarError: y not defined
Stacktrace:
 [1] macro expansion at /home/chad/.julia/packages/GeneralizedGenerated/X0aLF/src/closure_conv.jl:143 [inlined]
 [2] _rand(::Model{NamedTuple{(),T} where T<:Tuple,begin
    x ~ Normal(y, 1)
    y = f(x)
end}, ::NamedTuple{(),Tuple{}}) at /home/chad/.julia/packages/GeneralizedGenerated/X0aLF/src/closure_conv.jl:143
 [3] rand(::Soss.JointDistribution{NamedTuple{(),Tuple{}},NamedTuple{(),T} where T<:Tuple,begin
    x ~ Normal(y, 1)
    y = f(x)
end}) at /home/chad/git/jl/Soss/src/rand.jl:8
 [4] top-level scope at REPL[255]:1
```

I think the issue is that `f` is defined after the generated function, so it's not in scope.

> It's possible for people to define the function ouside model definitions and insert it. Is it what you want?

Ideally, anything in scope for the user would automatically also be in scope for the GG-related stuff. `$` interpolation would be ok,  but it would make things included in Soss feel special or magic, and it would be nice to avoid that if possible.

**Comment by thautwarm** [comment]
> [1] macro expansion at 
> /home/chad/.julia/packages/GeneralizedGenerated/X0aLF/src/closure_conv.jl:143 [inlined]


I noted this, I think it should be a bug after a glance.

**Comment by thautwarm** [comment]
Ahh,

```julia
    x = rand(Normal(y, 1))  # <- where will y come from...
    y = f(x)
    (y = y, x = x)
```

**Comment by thautwarm** [comment]
@cscherrer 

I think the root cause is at here,
At there: https://github.com/cscherrer/Soss.jl/blob/master/src/model.jl#L64

When merging two models, especially when the first argument is an `Assign`, 
this method is used: https://github.com/cscherrer/Soss.jl/blob/master/src/model.jl#L46

And I found that `m1` will get ignored once it's an `Assign`:
```julia
maybesomething(x::Any, y...) = x
```

**Comment by cscherrer** [comment]
Sorry, the example above was a silly mistake on my part. It should be something like this:

```julia
julia> rand(m)
ERROR: UndefVarError: f not defined
Stacktrace:
 [1] macro expansion at /home/chad/git/Soss.jl/src/rand.jl:12 [inlined]
 [2] rand(::Model{NamedTuple{(),T} where T<:Tuple,begin
    x ~ Normal()
    y = f(x)
    z ~ Normal(y, 1)
end}) at /home/chad/git/Soss.jl/src/rand.jl:12
 [3] top-level scope at REPL[10]:1

julia> sourceRand()(m)
quote
    x = rand(Normal())
    y = f(x)
    z = rand(Normal(y, 1))
    (y = y, x = x, z = z)
end
```

The issue I was trying to point out is that it would be nice to allow `f` to be used just by being in user scope. You can do it like this (below), but it's a bit awkward.

```julia
julia> m2 = @model f begin
           x ~ Normal()
           y = f(x)
           z ~ Normal(y,1)
       end;

julia> rand(m2(f=f))
(f = f, y = 2.129566505608441, x = 1.1295665056084412, z = 1.3485296270554956)
```

**Comment by thautwarm** [comment]
Hi Chad, when you have time, you can get started to add a field to `Model` types and acommodate the module(where `@model` gets invoked) object. And I'll manage to change the codegen ways to take advantage of the module object, to allow the generated code access expected globals variables.

**Comment by cscherrer** [comment]
That sounds great @thautwarm ! Just to be clear... Previously I had suggested,
> I think on the Soss side, I ought to be able to just add a field to the `Model` type, and then change the `@model` macro to ask for `_@MODULE_`. Then it will be available to pass to `@gg`

Your response:
> I think this way could be a bit difficult, because, Soss then should decide which variable is from the outer scope of current module.

Then I was running out of time and had to cut the discussion short.

But your latest comment (above) seems to indicate the approach I described could work. Am I reading that right?

**Comment by thautwarm** [comment]
Yes, it's feasible but needs some GG support to assure that `@model`  can invoke `@gg` in the correct module.

**Comment by thautwarm** [comment]
> Then it will be available to pass to @gg

Currently `@gg` does not allow you to custom the module used for codegen, and if you pass it as an argument, the type infer might get ruined and then performance can get reduced.

**Comment by cscherrer** [comment]
Rather than add a new field, it seems it would be convenient to represent this at the type level. That way, calling equivalent models from different modules still forces building the generated functions.

Here's a toy version of the idea:
```julia
julia> using GeneralizedGenerated: expr2typelevel

julia> struct Foo{M} end

julia> Foo{expr2typelevel(@__MODULE__)}()
Foo{Main}()
```

**Comment by cscherrer** [comment]
Closing in favor of #50
