### ISSUE TITLE
Warnings on startup, ok to ignore?

### ISSUE THREAD

**Issue by vasishth** [cscherrer/Soss.jl#47]
I'm a Julia newcomer, apologies if this is a dumb question. I got a lot of warnings on loading Soss. OK to ignore them? Using julia 1.2.

julia> using Soss
[ Info: Precompiling Soss [8ce77f84-9b61-11e8-39ff-d17a774bf41c]
┌ Warning: `lgamma(x::Real)` is deprecated, use `(logabsgamma(x))[1]` instead.
│   caller = lstirling_asym(::BigFloat) at misc.jl:56
└ @ StatsFuns ~/.julia/packages/StatsFuns/2QE7p/src/misc.jl:56

WARNING: using Lazy.flatten in module Soss conflicts with an existing identifier.

julia> 

julia> WARNING: both AdvancedHMC and Distributions export "Multinomial"; uses of it in module Soss must be qualified
WARNING: both SimpleGraphs and Distributions export "components"; uses of it in module Soss must be qualified
WARNING: both IterTools and DataFrames export "groupby"; uses of it in module Soss must be qualified
WARNING: both DataFrames and DataStructures export "head"; uses of it in module Soss must be qualified
WARNING: both SimpleGraphs and Distributions export "scale"; uses of it in module Soss must be qualified
WARNING: both DataFrames and NamedTupleTools export "select"; uses of it in module Soss must be qualified
WARNING: both DataFrames and SimplePosets export "stack"; uses of it in module Soss must be qualified
WARNING: both DataFrames and Lazy export "tail"; uses of it in module Soss must be qualified
julia>

**Comment by cscherrer** [comment]
Hi @vasishth, thanks for trying out Soss :)

Your question isn't dumb at all, thank you for bringing it up.

I haven't gotten these warnings, but my environment setup is probably different from yours. It's very helpful to know this is an issue. I'll make a pass through the code to check for this sort of thing.

Soss is currently at a stage I would consider "early beta". I think it for prototyping some models it should be ok to ignore these warnings, but it's not yet ready for production use.

**Comment by cscherrer** [comment]
Fixed in v0.8, please let me know if you still see this
