### ISSUE TITLE
Storing current module when calling `@model`

### ISSUE THREAD

**Issue by thautwarm** [cscherrer/Soss.jl#50]
```julia
julia> m1 = @model begin
                 x ~ N()
             end;
```

There're use cases that we need to define custom global variables outside module `Soss`, and currently all global variables are treated as in module `Soss`, which prevents the expected behaviours.

To end this, I propose to add an extra field `mod` to struct `Model`.

https://github.com/thautwarm/GeneralizedGenerated.jl/issues/24

**Comment by cscherrer** [comment]
Rather than add a new field, it seems it would be convenient to represent this at the type level. That way, calling equivalent models from different modules still forces building the generated functions.

Here's a toy version of the idea:
```julia
julia> using GeneralizedGenerated: expr2typelevel

julia> struct Foo{M} end

julia> getmodule(::Foo{M}) where M = M
getmodule (generic function with 1 method)

julia> Foo{expr2typelevel(@__MODULE__)}()
Foo{Main}()

julia> getmodule(ans)
Main
```

**Comment by cscherrer** [comment]
Hmm, this doesn't quite work as I had intended. `@__MODULE__` apparently answers, "what module contains the current code?", but I need something more like, "what module is _calling_ the current _function_?"

I don't see a way to `esc` it (yet, anyway)

**Comment by cscherrer** [comment]
Got it!
```julia
julia> m = @model begin
       x ~ Normal()
       end;

julia> typeof(m)
Model{NamedTuple{(),T} where T<:Tuple,begin
    x ~ Normal()
end,Main}

julia> Soss.getmodule(m)
Main
```

Now we need...

- `GeneralizedGenerated` support for specifying evaluation module
- Hooking things up the right way for Soss inference primitives

**Comment by thautwarm** [comment]
> Now we need...
> 
> * `GeneralizedGenerated` support for specifying evaluation module
> * Hooking things up the right way for Soss inference primitives

Yes!!!! Now we shared all context!

**Comment by cscherrer** [comment]
Done!! Thank you :)
