### ISSUE TITLE
Leaky `M`

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#67]
This works fine:
```julia
julia> m = @model J,μ begin
           x ~ For(J) do j
               Normal(μ[j],1)
           end
       end;

julia> rand(m(J=3,μ=randn(3)))
(J = 3, μ = [-1.0834777431935945, -0.25066269165681376, 1.2285812
342919462], x = [-1.2785760840079383, -0.10252931007812652, -0.83
70227365078675])
```

But when we try the same thing with `M`,

```julia
julia> m = @model M,μ begin
           x ~ For(M) do j
               Normal(μ[j],1)
           end
       end;

julia> rand(m(M=3,μ=randn(3)))
ERROR: type Int64 has no field rand
Stacktrace:
 [1] getproperty(::Int64, ::Symbol) at ./Base.jl:20
 [2] macro expansion at /home/chad/.julia/packages/GeneralizedGenerated/NDqgV/src/closure_conv.jl:121 [inlined]
 [3] _rand(::Type{TypeEncoding(Main)}, ::Model{NamedTuple{(:M, :μ),T} where T<:Tuple,TypeEncoding(begin
    x ~ For(M) do j
            Normal(μ[j], 1)
        end
end),TypeEncoding(Main)}, ::NamedTuple{(:M, :μ),Tuple{Int64,Array{Float64,1}}}) at /home/chad/.julia/packages/GeneralizedGenerated/NDqgV/src/closure_conv.jl:121
 [4] rand(::Soss.JointDistribution{NamedTuple{(:M, :μ),Tuple{Int64,Array{Float64,1}}},NamedTuple{(:M, :μ),T} where T<:Tuple,TypeEncoding(begin
    x ~ For(M) do j
            Normal(μ[j], 1)
        end
end),TypeEncoding(Main)}) at /home/chad/git/Soss.jl/src/primitives/rand.jl:7
 [5] top-level scope at REPL[23]:1
```

**Comment by thautwarm** [comment]
Yes, I should add a more hygienic alternative of `gg`!

**Comment by cscherrer** [comment]
For now, I should change `M` to `_M` (or something similar) so this is less likely to affect users.

@thautwarm , I'll reassign the Soss issue to myself. Is there a GG issue for this?

**Comment by thautwarm** [comment]
Sorry, I think I should immediately work on this now.  No GG issues.

**Comment by thautwarm** [comment]
It should be fine for us to workaround it in this way:

```julia
const M = gensym("A symbol to inspect a Soss model's global module")
@eval $M function (_::Type{$M}, ...) where M <: ...
    ...
end
```

**Comment by cscherrer** [comment]
Thanks @thautwarm ! Would you like me to try it, or are you getting a PR ready? Either is fine :)

I should note that tests are currently failing, because there are lots of changes so tests need updates. I think I'll cut tests down to the bare minimum and start re-populating them from there

**Comment by thautwarm** [comment]
We should wait until the tests passed, and then apply `M` to `$M` change. I can make a PR at that time.

**Comment by cscherrer** [comment]
Yeah, I think this is a good call. I'll scrap some tests for now to get to something that passes. Then building back up will be safer

**Comment by cscherrer** [comment]
CI is passing now. There's another issue I found while doing this that seems to be a scoping problem, I'll add a new issue for that
