### ISSUE TITLE
Rename exponentialFamilies.jl

### ISSUE THREAD

**Issue by sethaxen** [cscherrer/Soss.jl#76]
There are two files in `/src/` with the same name within a change in case: `exponentialFamilies.jl` and `exponentialfamilies.jl`. On systems that don't respect case like OS X, these names overwrite each other, and one can't stash changes in the repo. Changing one of the filenames should fix it.

**Comment by cscherrer** [comment]
Ok, thanks for bringing this up. I think both of these were just ideas anyway, but this issue will make it easier to track
