### ISSUE TITLE
Add author information

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss.jl#77]
The JOSS draft is [here](https://github.com/cscherrer/Soss.jl/tree/dev/writing/2019-JOSS).

@thautwarm can you add your information? To preview after pushing any changes, go [here](https://whedon.theoj.org/) and use repository `https://github.com/cscherrer/Soss.jl` and branch `dev`.

**Comment by thautwarm** [comment]
I'll ask my supervisor if I could use the affiliation of our Lab. If not I'll contact Microsoft Research Asia or other institutions I used to get involved in.

**Comment by thautwarm** [comment]
Hi, I asked my supervisor, and he is very supportive for my being a co-author of an international paper.
