### ISSUE TITLE
Would it be ok if I take a stab at SossModels.jl for StatisticalRethinking?

### ISSUE THREAD

**Issue by goedman** [cscherrer/Soss.jl#86]
Hi Chad, hope things are well for you! They certainly seem for Soss.jl. Your last 2 releases have worked well on my system so I've been thinking about trying all (or most at least) models in StatisticalRethinking in Soss.

As with StanModels, DynamicHMCModels and TuringModels, all part of the [StatisticalRethinkingJulia Github organization](https://github.com/StatisticalRethinkingJulia), I would like to do this in a repo SossModels.jl. Would that be ok with you?

This is a first step towards what I think of as StatisticalRethinking.jl v2 could be based upon, likely the combination Soss/DynamicHMC. I've seen you're also looking at Turing's AdvancedHMC, but
including Turing might make the list of dependencies pretty big.

Best,
Rob

**Comment by cscherrer** [comment]
Hi Rob,

Sorry for the delay, I'm just back in town from holiday travel.

I'd love to see more examples like this in Soss. @ode33 started on some of the "rethinking" models [here](https://github.com/ode33/Rethinking_Soss), could be good as a starting point or to compare against.

Would this be a registered package? The Statistical Rethinking models are pedagogically useful, but still a very narrow focus relative to the generality of the name "SossModels".

> I've seen you're also looking at Turing's AdvancedHMC, but including Turing might make the list of dependencies pretty big.

Sorry, I don't understand what you mean by this. Soss already depends on AdvancedHMC, but AdvancedHMC doesn't depend on Turing (dependency goes the other direction).

**Comment by goedman** [comment]
Thanks Chad.

I'll check with Olivier. 

Your point about SossModels is valid, so I won't publish the package. Let me know if you would like to use that name, then I'll rename it. In the end, if my plan works out for v2 of StatisticalRethinking, the models in SossModels would be integrated into StatisticalRethinking.jl and this version of SossModels removed.

AdvancedHMC is definitely a lot better than all of Turing, but still, AdvancedHMC, Sympy. Yes, I have certainly gotten pretty paranoid about dependencies... Anyway, comes with the territory.
